"""Generate reconciled JSON, LaTeX macros, and the README results block."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent
RESULTS = ROOT / "data" / "revision_results"
README = ROOT / "README.md"
TEX_MACROS = ROOT / "paper" / "generated_results.tex"
START = "<!-- REVISION_RESULTS_START -->"
END = "<!-- REVISION_RESULTS_END -->"


def r3(value: float) -> str:
    return f"{value:.3f}"


def load(name: str) -> dict:
    return json.loads((RESULTS / name).read_text())


def headline(data: dict, config: str) -> dict:
    cell = data["configurations"][config]["cutoffs"]["10"]
    return {
        "jaccard": cell["en_id_consistency"]["mean_jaccard"],
        "overlap_at_10": cell["en_id_consistency"]["mean_overlap_at_k"],
        "id_judgment_coverage": cell["effectiveness"]["id"]["judgment_coverage"],
        "en_ndcg_at_10": cell["effectiveness"]["en"]["ndcg"],
        "id_ndcg_at_10": cell["effectiveness"]["id"]["ndcg"],
    }


def main() -> None:
    original, formal, comparison = load("original.json"), load("formal-id-v1.json"), load("comparison.json")
    configs = ("clip/raw", "mclip/raw", "bm25/raw", "clip/calibrated", "mclip/calibrated")
    summary = {
        "schema_version": 1,
        "source_files": ["original.json", "formal-id-v1.json", "comparison.json"],
        "top_10": {
            "original": {config: headline(original, config) for config in configs},
            "formal-id-v1": {config: headline(formal, config) for config in configs},
        },
        "paired_jaccard_robustness_top_10": {
            config: comparison["configurations"][config]["10"]["paired_query_jaccard"]
            for config in configs
        },
        "interpretation": {
            "formal_effectiveness_comparability": "limited_by_incomplete_judgment_pool",
            "human_validation": "future_work",
            "assessor": "single_llm_provisional",
        },
    }
    (RESULTS / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")

    o, f = summary["top_10"]["original"], summary["top_10"]["formal-id-v1"]
    macros = ["% Generated by generate_revision_report.py; do not edit manually."]
    macro_values = {
        "OriginalClipJaccard": o["clip/raw"]["jaccard"],
        "OriginalMclipJaccard": o["mclip/raw"]["jaccard"],
        "OriginalBmTwentyFiveEnNdcg": o["bm25/raw"]["en_ndcg_at_10"],
        "OriginalBmTwentyFiveIdNdcg": o["bm25/raw"]["id_ndcg_at_10"],
        "FormalClipJaccard": f["clip/raw"]["jaccard"],
        "FormalMclipJaccard": f["mclip/raw"]["jaccard"],
        "FormalBmTwentyFiveJaccard": f["bm25/raw"]["jaccard"],
        "FormalClipLabelCoverage": f["clip/raw"]["id_judgment_coverage"],
        "FormalMclipLabelCoverage": f["mclip/raw"]["id_judgment_coverage"],
        "FormalBmTwentyFiveLabelCoverage": f["bm25/raw"]["id_judgment_coverage"],
        "OriginalBmTwentyFiveJaccard": o["bm25/raw"]["jaccard"],
        "OriginalClipCalibratedJaccard": o["clip/calibrated"]["jaccard"],
        "FormalClipCalibratedJaccard": f["clip/calibrated"]["jaccard"],
        "OriginalMclipCalibratedJaccard": o["mclip/calibrated"]["jaccard"],
        "FormalMclipCalibratedJaccard": f["mclip/calibrated"]["jaccard"],
        "FormalClipCalibratedLabelCoverage": f["clip/calibrated"]["id_judgment_coverage"],
        "FormalMclipCalibratedLabelCoverage": f["mclip/calibrated"]["id_judgment_coverage"],
        "FormalMclipJaccardDifference": summary["paired_jaccard_robustness_top_10"]["mclip/raw"]["mean_difference_formal_minus_original"],
        "FormalMclipCalibratedJaccardDifference": summary["paired_jaccard_robustness_top_10"]["mclip/calibrated"]["mean_difference_formal_minus_original"],
    }
    percentage_macros = {name for name in macro_values if name.endswith("LabelCoverage")}
    for name, value in macro_values.items():
        rendered = f"{value * 100:.1f}" if name in percentage_macros else r3(value)
        macros.append(f"\\newcommand{{\\{name}}}{{{rendered}}}")
    TEX_MACROS.write_text("\n".join(macros) + "\n")

    rows = []
    labels = {"clip/raw": "CLIP raw", "mclip/raw": "mCLIP raw", "bm25/raw": "BM25",
              "clip/calibrated": "CLIP calibrated", "mclip/calibrated": "mCLIP calibrated"}
    for config in configs:
        rows.append(f"| {labels[config]} | {r3(o[config]['jaccard'])} | {r3(f[config]['jaccard'])} | "
                    f"{f[config]['id_judgment_coverage'] * 100:.1f}% |")
    block = "\n".join([
        START,
        "### Reconciled query-robustness results",
        "",
        "Generated from `data/revision_results/summary.json` at top-10. Revised-query effectiveness is not directly comparable because the original judgment pool has incomplete coverage.",
        "",
        "| Configuration | Original EN/ID Jaccard | Formal-ID EN/ID Jaccard | Formal-ID judgment coverage |",
        "|---|---:|---:|---:|",
        *rows,
        END,
    ])
    text = README.read_text()
    if START not in text or END not in text:
        text = text.rstrip() + "\n\n" + block + "\n"
    else:
        text = text[:text.index(START)] + block + text[text.index(END) + len(END):]
    README.write_text(text)
    print(f"Wrote {RESULTS / 'summary.json'}, {TEX_MACROS}, and README results block")


if __name__ == "__main__":
    main()
